version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  #pre_build:
  #  commands:
  #  - echo Running unit tests
  #  - ./mvnw spring-boot:test
  build:
    commands:
    - echo Build started on `date`
    - ./mvnw -B package
  post_build:
    commands:
    - echo Build completed on `date`
artifacts:
  files:
  - target/spring-petclinic-*.jar
  base-directory: 'target'
  name: spring-petclinic_$CODEBUILD_BUILD_NUMBER-$(date +%Y-%m-%d)
  discard-paths: yes
